%% Create the study and precompute measures
% - select brain components (previously chosen subject by subject using
% brain_comp_select.m)
% - epoch datasets
% - create eeglab STUDY
% - precompute component measures for clustering (warning: this takes
% awhile)

clear all

[folder, name, ext] = fileparts(which('create_study.m'));
cd([folder '/'])
home;
current_folder = pwd;
addpath(genpath(current_folder))

mypath = ([current_folder '/']);
eeglabpath = ([current_folder '/eeglab13_6_5b/']);
addpath(eeglabpath)
eeglab

mypath = [folder, '/pp/STUDY/'];

SUBJECT = {'S01' 'S03' 'S04' 'S05' 'S06' 'S07' 'S09' 'S10' 'S11' 'S12' 'S13' 'S14' 'S15' 'S16' 'S17' 'S18' 'S19' 'S20'};
sub = {'01' '03' '04' '05' '06' '07' '09' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20'}; 
f_sub = [1 3 4 5 6 7 9 10 11 12 13 14 15 16 17 18 19 20];

Comps = {[2 3 4 13 21 22 24 28 32 34],...
    [3 4 7 20 36 55],...
    [1 2 3 4 5 6 8 11 12 13 14 15 17 22 24 28 34 38],...
    [2 3 4 5 6 7 8 9 13 14 15 18 19 23 34 55],... 
    [2 3 4 6 7 8 9 13 15 20 22 33],... 
    [2 6 8 11 12 14 17 31 32 33 36],...
    [1 2 3 4 5 6 7 8 9 11 12 15 21 23 29 34 35 39 40],...
    [3 6 10 11 12 14 20 21 22 23 24 26 28 33 36],...
    [1 4 5 6 8 11 12 13 17 18 19 23 37 41],...
    [2 3 4 7 8 9 10 11 12 13 15 16 20 23 24 26 43 45],... 
    [3 4 5 6 7 8 9 10 18 23 25 29 33 37],... 
    [3 4 12 14 20 24 25 28 32 36 39 41 42],...
    [3 4 6 7 8 11 12 13 14 15 17 18 22 26 29 34],... 
    [1 2 4 5 6 10 11 12 13 15 21 22 26 27 28 29 30 36 39 41 43 44],... 
    [2 3 5 6 12 14 17 19 26 27 32 33 35 37 41 45],...
    [2 4 5 6 8 9 10 12 13 15 17 26 27 39 48],... 
    [1 2 4 5 6 11 12 13 14 16 18 24 26 32 46 52],... 
    [2 3 5 6 7 8 11 12 15 16 17 19 20 21 26],...
   };


%%
for s = 1:numel(sub)
    
    clear EEG_STOP EEG_WM 
    
    %% reload individual datasets with ICA weights and dipoles
    loadpath = [folder, '/pp/s', num2str(f_sub(s)), '/'];
    
    EEG_STOP = pop_loadset(['S', num2str(f_sub(s)), '_STOP_ica.set'],[loadpath]);
    EEG_WM = pop_loadset(['S', num2str(f_sub(s)), '_WM_ica.set'],[loadpath]);
        
    %% Keep brain components
    clear SUBCOMPS
    SUBCOMPS =  find(ismember(1:size(EEG_STOP.icaact,1), Comps{s})==0);
    EEG_STOP = pop_subcomp( EEG_STOP, SUBCOMPS, 0);
    EEG_STOP = eeg_checkset(EEG_STOP);
    
    EEG_WM = pop_subcomp( EEG_WM, SUBCOMPS, 0);
    EEG_WM = eeg_checkset(EEG_WM);
       
    %% epoch datasets relative to the tone for retrocue
    EEG_S = pop_epoch( EEG_WM, {  '65530'  }, [-1  2.5], 'epochinfo', 'yes');
    EEG_S = eeg_checkset(EEG_S);
    
    EEG_N = pop_epoch( EEG_WM, {  '65529'  }, [-1  2.5], 'epochinfo', 'yes');
    EEG_N = eeg_checkset(EEG_N);
    
    %% epoch datasets relative to the stop signal for stop signal task
    EEG_SUCCESS = pop_epoch( EEG_STOP, {  '65590'  }, [-2  3.5], 'epochinfo', 'yes');
    EEG_SUCCESS = eeg_checkset(EEG_SUCCESS); 
    EEG_SUCCESS = pop_epoch( EEG_SUCCESS, {  '65532'  }, [-1  2.5], 'epochinfo', 'yes');
    EEG_SUCCESS = eeg_checkset(EEG_SUCCESS);
    
    EEG_FAIL = pop_epoch( EEG_STOP, {  '65580'  }, [-2  3.5], 'epochinfo', 'yes');
    EEG_FAIL = eeg_checkset(EEG_FAIL); 
    EEG_FAIL = pop_epoch( EEG_FAIL, {  '65532'  }, [-1  2.5], 'epochinfo', 'yes');
    EEG_FAIL = eeg_checkset(EEG_FAIL);
    
    %% save datasets
    EEG_S = pop_saveset( EEG_S,['S' sub{s} '_WM_STAND_ica.set'], mypath);
    EEG_N = pop_saveset( EEG_N,['S' sub{s} '_WM_NOVEL_ica.set'], mypath);
    EEG_SUCCESS = pop_saveset( EEG_SUCCESS,['S' sub{s} '_STOP_SUCC_ica.set'], mypath);
    EEG_FAIL = pop_saveset( EEG_FAIL,['S' sub{s} '_STOP_FAIL_ica.set'], mypath);
    
    %% save overall datasets
    EEG_STOP = pop_saveset( EEG_STOP,['S' sub{s} '_STOP_brain_ica.set'], loadpath);
    EEG_WM = pop_saveset( EEG_WM,['S' sub{s} '_WM_brain_ica.set'], loadpath);

end

%% set memory options in eeglab
pop_editoptions( 'option_storedisk', 1, 'option_savetwofiles', 1, 'option_saveversion6', 1, 'option_single', ...
    0, 'option_memmapdata', 0, 'option_eegobject', 0, 'option_computeica', 1, 'option_scaleicarms', 1, 'option_rememberfolder', ...
    1, 'option_donotusetoolboxes', 0, 'option_checkversion', 1, 'option_chat', 0);

%% create study using novel trials, standard trials, SS trials and FS trials
[STUDY, ALLEEG] = std_editset( STUDY, ALLEEG,  'name', 'RETROCUE_STUDY', 'commands',...
{{ 'index',1, 'load', [mypath SUBJECT{1}  '_WM_STAND_ica.set'], 'subject', SUBJECT{1} , 'session',1, 'condition', 'standard'},...
{ 'index',2, 'load', [mypath SUBJECT{1}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{1} , 'session',1, 'condition', 'novel'},...
{ 'index',3, 'load', [mypath SUBJECT{1}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{1} , 'session',1, 'condition', 'failed stop'},...
{ 'index',4, 'load', [mypath SUBJECT{1}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{1} , 'session',1, 'condition', 'succ stop'},...
{ 'index',5, 'load', [mypath SUBJECT{2}  '_WM_STAND_ica.set'], 'subject', SUBJECT{2} , 'session',1, 'condition', 'standard'},...
{ 'index',6, 'load', [mypath SUBJECT{2}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{2} , 'session',1, 'condition', 'novel'},...
{ 'index',7, 'load', [mypath SUBJECT{2}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{2} , 'session',1, 'condition', 'failed stop'},...
{ 'index',8, 'load', [mypath SUBJECT{2}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{2} , 'session',1, 'condition', 'succ stop'},...
{ 'index',9, 'load', [mypath SUBJECT{3}  '_WM_STAND_ica.set'], 'subject', SUBJECT{3} , 'session',1, 'condition', 'standard'},...
{ 'index',10, 'load', [mypath SUBJECT{3}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{3} , 'session',1, 'condition', 'novel'},...
{ 'index',11, 'load', [mypath SUBJECT{3}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{3} , 'session',1, 'condition', 'failed stop'},...
{ 'index',12, 'load', [mypath SUBJECT{3}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{3} , 'session',1, 'condition', 'succ stop'},...
{ 'index',13, 'load', [mypath SUBJECT{4}  '_WM_STAND_ica.set'], 'subject', SUBJECT{4} , 'session',1, 'condition', 'standard'},...
{ 'index',14, 'load', [mypath SUBJECT{4}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{4} , 'session',1, 'condition', 'novel'},...
{ 'index',15, 'load', [mypath SUBJECT{4}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{4} , 'session',1, 'condition', 'failed stop'},...
{ 'index',16, 'load', [mypath SUBJECT{4}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{4} , 'session',1, 'condition', 'succ stop'},...
{ 'index',17, 'load', [mypath SUBJECT{5}  '_WM_STAND_ica.set'], 'subject', SUBJECT{5} , 'session',1, 'condition', 'standard'},...
{ 'index',18, 'load', [mypath SUBJECT{5}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{5} , 'session',1, 'condition', 'novel'},...
{ 'index',19, 'load', [mypath SUBJECT{5}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{5} , 'session',1, 'condition', 'failed stop'},...
{ 'index',20, 'load', [mypath SUBJECT{5}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{5} , 'session',1, 'condition', 'succ stop'},...
{ 'index',21, 'load', [mypath SUBJECT{6}  '_WM_STAND_ica.set'], 'subject', SUBJECT{6} , 'session',1, 'condition', 'standard'},...
{ 'index',22, 'load', [mypath SUBJECT{6}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{6} , 'session',1, 'condition', 'novel'},...
{ 'index',23, 'load', [mypath SUBJECT{6}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{6} , 'session',1, 'condition', 'failed stop'},...
{ 'index',24, 'load', [mypath SUBJECT{6}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{6} , 'session',1, 'condition', 'succ stop'},...
{ 'index',25, 'load', [mypath SUBJECT{7}  '_WM_STAND_ica.set'], 'subject', SUBJECT{7} , 'session',1, 'condition', 'standard'},...
{ 'index',26, 'load', [mypath SUBJECT{7}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{7} , 'session',1, 'condition', 'novel'},...
{ 'index',27, 'load', [mypath SUBJECT{7}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{7} , 'session',1, 'condition', 'failed stop'},...
{ 'index',28, 'load', [mypath SUBJECT{7}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{7} , 'session',1, 'condition', 'succ stop'},...
{ 'index',29, 'load', [mypath SUBJECT{8}  '_WM_STAND_ica.set'], 'subject', SUBJECT{8} , 'session',1, 'condition', 'standard'},...
{ 'index',30, 'load', [mypath SUBJECT{8}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{8} , 'session',1, 'condition', 'novel'},...
{ 'index',31, 'load', [mypath SUBJECT{8}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{8} , 'session',1, 'condition', 'failed stop'},...
{ 'index',32, 'load', [mypath SUBJECT{8}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{8} , 'session',1, 'condition', 'succ stop'},...
{ 'index',33, 'load', [mypath SUBJECT{9}  '_WM_STAND_ica.set'], 'subject', SUBJECT{9} , 'session',1, 'condition', 'standard'},...
{ 'index',34, 'load', [mypath SUBJECT{9}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{9} , 'session',1, 'condition', 'novel'},...
{ 'index',35, 'load', [mypath SUBJECT{9}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{9} , 'session',1, 'condition', 'failed stop'},...
{ 'index',36, 'load', [mypath SUBJECT{9}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{9} , 'session',1, 'condition', 'succ stop'},...
{ 'index',37, 'load', [mypath SUBJECT{10}  '_WM_STAND_ica.set'], 'subject', SUBJECT{10} , 'session',1, 'condition', 'standard'},...
{ 'index',40, 'load', [mypath SUBJECT{10}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{10} , 'session',1, 'condition', 'novel'},...
{ 'index',41, 'load', [mypath SUBJECT{10}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{10} , 'session',1, 'condition', 'failed stop'},...
{ 'index',42, 'load', [mypath SUBJECT{10}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{10} , 'session',1, 'condition', 'succ stop'},...
{ 'index',43, 'load', [mypath SUBJECT{11}  '_WM_STAND_ica.set'], 'subject', SUBJECT{11} , 'session',1, 'condition', 'standard'},...
{ 'index',44, 'load', [mypath SUBJECT{11}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{11} , 'session',1, 'condition', 'novel'},...
{ 'index',45, 'load', [mypath SUBJECT{11}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{11} , 'session',1, 'condition', 'failed stop'},...
{ 'index',46, 'load', [mypath SUBJECT{11}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{11} , 'session',1, 'condition', 'succ stop'},...
{ 'index',47, 'load', [mypath SUBJECT{12}  '_WM_STAND_ica.set'], 'subject', SUBJECT{12} , 'session',1, 'condition', 'standard'},...
{ 'index',48, 'load', [mypath SUBJECT{12}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{12} , 'session',1, 'condition', 'novel'},...
{ 'index',49, 'load', [mypath SUBJECT{12}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{12} , 'session',1, 'condition', 'failed stop'},...
{ 'index',50, 'load', [mypath SUBJECT{12}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{12} , 'session',1, 'condition', 'succ stop'},...
{ 'index',51, 'load', [mypath SUBJECT{13}  '_WM_STAND_ica.set'], 'subject', SUBJECT{13} , 'session',1, 'condition', 'standard'},...
{ 'index',52, 'load', [mypath SUBJECT{13}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{13} , 'session',1, 'condition', 'novel'},...
{ 'index',53, 'load', [mypath SUBJECT{13}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{13} , 'session',1, 'condition', 'failed stop'},...
{ 'index',54, 'load', [mypath SUBJECT{13}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{13} , 'session',1, 'condition', 'succ stop'},...
{ 'index',55, 'load', [mypath SUBJECT{14}  '_WM_STAND_ica.set'], 'subject', SUBJECT{14} , 'session',1, 'condition', 'standard'},...
{ 'index',56, 'load', [mypath SUBJECT{14}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{14} , 'session',1, 'condition', 'novel'},...
{ 'index',57, 'load', [mypath SUBJECT{14}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{14} , 'session',1, 'condition', 'failed stop'},...
{ 'index',58, 'load', [mypath SUBJECT{14}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{14} , 'session',1, 'condition', 'succ stop'},...
{ 'index',59, 'load', [mypath SUBJECT{15}  '_WM_STAND_ica.set'], 'subject', SUBJECT{15} , 'session',1, 'condition', 'standard'},...
{ 'index',60, 'load', [mypath SUBJECT{15}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{15} , 'session',1, 'condition', 'novel'},...
{ 'index',61, 'load', [mypath SUBJECT{15}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{15} , 'session',1, 'condition', 'failed stop'},...
{ 'index',62, 'load', [mypath SUBJECT{15}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{15} , 'session',1, 'condition', 'succ stop'},...
{ 'index',63, 'load', [mypath SUBJECT{16}  '_WM_STAND_ica.set'], 'subject', SUBJECT{16} , 'session',1, 'condition', 'standard'},...
{ 'index',64, 'load', [mypath SUBJECT{16}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{16} , 'session',1, 'condition', 'novel'},...
{ 'index',65, 'load', [mypath SUBJECT{16}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{16} , 'session',1, 'condition', 'failed stop'},...
{ 'index',66, 'load', [mypath SUBJECT{16}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{16} , 'session',1, 'condition', 'succ stop'},...
{ 'index',67, 'load', [mypath SUBJECT{17}  '_WM_STAND_ica.set'], 'subject', SUBJECT{17} , 'session',1, 'condition', 'standard'},...
{ 'index',68, 'load', [mypath SUBJECT{17}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{17} , 'session',1, 'condition', 'novel'},...
{ 'index',69, 'load', [mypath SUBJECT{17}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{17} , 'session',1, 'condition', 'failed stop'},...
{ 'index',70, 'load', [mypath SUBJECT{17}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{17} , 'session',1, 'condition', 'succ stop'},...
{ 'index',71, 'load', [mypath SUBJECT{18}  '_WM_STAND_ica.set'], 'subject', SUBJECT{18} , 'session',1, 'condition', 'standard'},...
{ 'index',72, 'load', [mypath SUBJECT{18}  '_WM_NOVEL_ica.set'], 'subject', SUBJECT{18} , 'session',1, 'condition', 'novel'},...
{ 'index',73, 'load', [mypath SUBJECT{18}  '_STOP_FAIL_ica.set'], 'subject', SUBJECT{18} , 'session',1, 'condition', 'failed stop'},...
{ 'index',74, 'load', [mypath SUBJECT{18}  '_STOP_SUCC_ica.set'], 'subject', SUBJECT{18} , 'session',1, 'condition', 'succ stop'},...
},...
'updatedat', 'on', 'savedat', 'on' );

%% save study    
[STUDY EEG] = pop_savestudy( STUDY, EEG, 'filename','RETROCUE_STUDY.study','filepath',mypath);

%% precompute component measures
[STUDY ALLEEG] = std_precomp(STUDY, ALLEEG, 'components','recompute','on',...
    'erp','on','erpparams', {'rmbase' [-200 0] },...
    'scalp','on',...
    'spec','on','specparams',{'specmode' 'fft' 'logtrials' 'off'},...
    'ersp','on',...
    'erspparams',{'type', 'ersp', 'cycles', [3 0.5], 'freqs', [3 60], 'padratio',4, 'ntimesout', 300});
